sudo: required
language: java
jdk: oraclejdk8
install: true
cache:
    directories:
    - $HOME/.m2
script:
  - mvn -f ./parking_reservation_1.0 install clean -DskipTests=true
  - bash <(curl -s https://codecov.io/bash)

